services:
  redpanda:
    container_name: kafka
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1                   # single core
      - --memory 256M            # RAM limit
      - --overprovisioned        # disable some performance checks
      - --node-id 0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

    # kafka:
    #     container_name: kafka
    #     image: bitnami/kafka:4.0.0-debian-12-r3
    #     ports:
    #         - "9092:9092"
    #     environment:
    #         KAFKA_CFG_NODE_ID: 1
    #         KAFKA_CFG_PROCESS_ROLES: broker, controller
    #         KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    #         KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    #         KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    #         KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    #         KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    #     healthcheck:
    #         test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
    #         interval: 20s
    #         timeout: 10s
    #         retries: 10
    #     networks:
    #         - default

networks:
  default:
    external:
      name: neura-query-shared-net
